name: Deploy and Run Debug Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Keep the deploy job, but it will only run manually now
    # if: github.event_name == 'push' # This condition is no longer needed
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Replit
      uses: replitapi/deploy-action@v1
      with:
        repl-id: ${{ secrets.REPL_ID }}
        token: ${{ secrets.REPLIT_TOKEN }}

  analyze:
    runs-on: ubuntu-latest
    # This job will also only run manually now
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Debug Service
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: node dist/services/issue-analyzer.js
